name: aerotec_flutter_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  camera_camera: ^2.0.1
  cupertino_icons: ^1.0.2
  cloud_firestore: ^2.2.1
  datetime_picker_formfield: ^2.0.0
  firebase_auth: "^1.3.0"
  firebase_core: ^1.2.1
  firebase_storage: "^8.1.1"
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.7
  google_fonts: ^2.1.0
  image_picker: ^0.7.4
  permission_handler: ^6.1.1
  photo_view: ^0.12.0
  provider: ^5.0.0
  google_maps_flutter: ^2.1.0
  # qr_code_scanner: ^0.3.5
  
  
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
   - images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
